### ISSUE TITLE
Final Project Proposal

### ISSUE THREAD

**Issue by raymasaki** [raymasaki/banger_gallery#1]
@WilliamfShaw @jasonseminara @zhenpanda @amcooper 

Final Project Proposal:
https://github.com/raymasaki/banger_gallery/blob/development/PROPOSAL.md

Research/Process/Inspiration/Technologies/etc.:
https://github.com/raymasaki/banger_gallery/blob/development/README.md

**Comment by jasonseminara** [comment]
As we discussed, I think this is a great idea, and represents a thesis. 

This site could/should be a collection of interactive (viz) observations (your experiments), showing some correlation that supports your overall thesis. This could be in the form of interactive data viz.

The individual observations (eg, use of purple by certain artists; minimalism over time, or as a reaction to a certain album) should be clearly defined and absorbable by any user who has not done the extensive research. 

The website could serve as a proving ground for your hypothesis: it would culminate with some resolution proving your thesis.
